spring.application.name=siw-palestra

spring.datasource.url=jdbc:postgresql://localhost:5432/siw_palestra
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google OAuth2 Credentials
spring.security.oauth2.client.registration.google.client-id=218219519833-tvmb8h601dc2690jbof77gnep6slaihs.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
